### PR TITLE
Add configuration to always show prev/next buttons

### PR DESCRIPTION
**Pull request by jacktrades**
This adds 2 props to Paginator:

- alwaysShowPrevNext (bool): Always show prev/next buttons even if the
  page is the first or last, respectively.
- inactiveClassName (string): Class name to add to the prev/next buttons
  if they should be considered inactive (e.g., the prev button should be
  inactive if page is the first page).

### CODE REVIEW

**Comment by jacktrades** [comment]
@bebraw if you're interested in adding the ability to always show the prev/next buttons, here's a patch.  I added this to the demo app mainly for testing, you may not want it there permanently.  If there are any changes you'd like to see, just let me know.

I'm still in the process of evaluating this library for my project, so there's no rush (or even need) to merge this.  After implementing this, I realized I might need a paginator with a fixed number of pages (including ellipses), and I'm not sure that's a trivial patch to this project.  Example:

```
< *1*  2   3   4   5  ...  9  >
<  1  *2*  3   4   5  ...  9  >
<  1   2  *3*  4   5  ...  9  >
<  1   2   3  *4*  5  ...  9  >
<  1  ...  4  *5*  6  ...  9  >
<  1  ...  5  *6*  7   8   9  >
<  1  ...  5   6  *7*  8   9  >
<  1  ...  5   6   7  *8*  9  >
<  1  ...  5   6   7   8  *9* >
```

**Comment by bebraw** [comment]
@jacktrades What if we made it possible to swap the pagination algorithm? It's always good if you can solve some of these things at the user space while benefitting from the basic structure and markup.

**Comment by jacktrades** [comment]
That was my initial thought too.  The biggest problem I see with that is adding complexity to the interface.  Maybe there's some common ground we can establish for parameters to the pagination algorithms...

For example, the current algorithm (if I'm understanding it correctly) allows you to set the number of pages to show at the beginning/end, but the number of pages to show in the "center" is fixed (to 3, the selected page, and one to either side of it).  So the relevant configuration parameters would be `beginPages` and `endPages`.

The algorithm I have in mind would allow you to configure the number of pages to the left and right of the selection, let's say `leftPages` and `rightPages`.  Originally, I was thinking `beginPages` and `endPages` would be fixed at 1, but there's no reason they *need* to be, it just adds another 2 parameters to the minimum pages calculation, which would be something like (excuse my math): `(beginPages + 1) + (endPages + 1) + (leftPages + rightPages + 1)`.

So a common configuration might be something like:

```
propTypes: {
    paginator: React.PropTypes.function,  // the pagination algorithm
    beginPages: React.PropTypes.number,  // number of pages at the beginning of the range
    endPages: React.PropTypes.number,  // number of pages at the end of the range
    leftPages: React.PropTypes.number,  // number of pages to the left of the selection
    rightPages: React.PropTypes.number,  // number of pages to the right of the selection
    page: React.PropTypes.number,  // current page
    totalPages: React.PropTypes.number,  // total pages

```

Personally, I'd like to see the signature of `paginator` become more explicit, instead of passing props to it directly, maybe something like:

```
function arbitraryPaginator(page, totalPages, opts) { ... }
```

Where `opts` is an object of optional values for the `*Pages` parameters, that each pagination algorithm is expected to define sane defaults for.

I'm not sure if that covers the "general" use-case, but I think it adequately covers both the current and my intended use-cases.  Thoughts?

**Comment by bebraw** [comment]
What if we let `Paginator` simply to consume segments? After that you'll use `segmentize` or its variant to generate those. This will clean up the interface massively.

**Comment by jacktrades** [comment]
I think I like where you're going with that.  What might that interface look like?

**Comment by bebraw** [comment]
> I think I like where you're going with that. What might that interface look like?

Simply pass `segments: React.propTypes.Array`. So instead of `var segments = segmentize(this.props);` we just consume the segments through a prop.

**Comment by jacktrades** [comment]
That would mean the user would have to do something like:

```
render() {
    // ...
    var paginated = Paginator.paginate(data, pagination);
    var segments = Paginator.segmentize(...);
    return (
          <Paginator
                    segments={segments}
                    showPrevNext={true}
                    onSelect={this.onSelect}></Paginator>
    );
```

**Comment by jacktrades** [comment]
Ooops, hit send too early...

I kind-of like that.  You can default to a sane segmenter if `segments` isn't provided.  Then let the user override with whatever they want, and you don't even have to force a function signature on them for the segmenter.  I think I'm sold on that.

**Comment by bebraw** [comment]
Yeah. Do you want to alter the PR? Maybe I should accept this one first and then we do another one for `segments`?

**Comment by jacktrades** [comment]
Yeah, let's consider this a stand-alone patch.  My current client doesn't have the fixed-width paginator as a requirement (I do for a personal project), so it might be a bit before I can devote time to this.

**Comment by bebraw** [comment]
> Yeah, let's consider this a stand-alone patch. My current client doesn't have the fixed-width paginator as a requirement (I do for a personal project), so it might be a bit before I can devote time to this.

Alright. I pushed out `0.9.0` with your changes. It feels like we should redesign `Paginator` interface for `1.0.0`. Extracting `segments` is a good first step. Perhaps we can extract something more. The current component is too bloated for my tastes.

**Pull request merged**
