### PR TITLE
Add next & previous buttons

### PR DESCRIPTION
**Pull request by nadavspi**
- Toggled with `showPrevNext` prop
- Class names controlled with `prevClassName` and `nextClassName` props
- Next doesn't display on last page, Previous doesn't display on first page

### CODE REVIEW

**Comment by bebraw** [comment]
Nice! Thanks. There's a new version (0.6.4) with the change out.

Do you want that I add you as a collaborator to the project? We probably should still go through PRs or at least discuss through issues if you have bigger changes in mind. Small changes can go directly to master.

**Comment by nadavspi** [comment]
That was quick. Thanks!

**Comment by nadavspi** [comment]
Up to you — I'm fine with submitting PRs.

**Comment by bebraw** [comment]
> Up to you — I'm fine with submitting PRs.

Added.

The site is a little cruddy atm etc. but keep on doing what you think is the best and fits your needs. I'll try to provide feedback and help as best I can. :+1:

**Pull request merged**
