### PR TITLE
Labels for prev and next buttons added

### PR DESCRIPTION
**Pull request by codexorange**
Two props (prevButtonLabel, nextButtonLabel) are added for display in
each buttons. This label can be html tag in string.

### CODE REVIEW

**Comment by codexorange** [comment]
Well, I thought it would be laborious to have to declare a variable that contains the entire element, including events (correct me if I'm wrong). Also, I doubt that need to customize or change anything apart from the button label.

**Comment by bebraw** [comment]
@codexorange Ah, that's a valid point. Note that we can get rid of `dangerouslySetInnerHTML` doing `<a href="#" ...>{ this.props.prevButtonLabel ? this.props.prevButtonLabel : 'Prev' }</a>` kind of thing too. That would achieve both goals.

**Comment by codexorange** [comment]
I not found the way to avoid use `dangerouslySetInnerHTML`. E.g.

```
var prevButtonLabel = '<i class="fa fa-arrow-left"></i>';
var nextButtonLabel = '<i class="fa fa-arrow-right"></i>';

<Paginator
    ...
    prevButtonLabel={prevButtonLabel}
    nextButtonLabel={nextButtonLabel}
    onSelect={this.onSelect} />
```

The result without using `dangerouslySetInnerHTML` it would be

`<i class="fa fa-arrow-left"></i> [1] [2] [3] ... [12] [13] [14] <i class="fa fa-arrow-right"></i>`

**Comment by bebraw** [comment]
I went with the general idea. You should be able to do

```javascript
...
prevButton={<i class="fa fa-arrow-left" />}
nextButton={<i class="fa fa-arrow-right" />}
...
```

now.

**Pull request closed without merging**
